const Board = require("../models/boardModel");
const mongoose = require('mongoose');

const boardController = {};

// this needs to be called, but it seems that we need a router for this particular post request
// /boards/post is the endpoint Clark said
// this generates Id that can be grabbed by router
// don't need to worry about adding it to User, use another middleware for that function
boardController.createBoard = (req, res, next) => {
  console.log('inside of boardController.createBoard. Req.body: ', req.body);
  // since the schema requires these, this will be send through req body
  const { boardName, columnName, cardText } = req.body;
  // so i want to send board ID back as well, because I noticed that boards in DB has _id: ObjectId('6406897254f6667a95770854') for goblin shark
  // id of board is autogenerated
  Board.create({boardName, columnName, cardText})
    .then(data => {
      res.locals.board = data;
      next();
    })
    .catch(err => {
      return next({
        log: "error in boardController.createBoards",
        message: { err: "boardController.createBoards" + err },
      });
    });
};

boardController.getBoards = (req, res, next) => {
  console.log('running boardController.getBoard. res.locals: ', res.locals)
  let { boardIds } = res.locals;

  Board.find({_id: {$in: boardIds}})
    .then(response => {
      res.locals.boards = response;
      return next();
    })
    .catch((err) => {
      return next({
        log: "error in boardController.getBoards",
        message: { err: "boardController.getBoards" + err },
      });
    });
};

module.exports = boardController;
