const Board = require("../models/boardModel");
const mongoose = require('mongoose');

const boardController = {};

// this needs to be called, but it seems that we need a router for this particular post request
// /boards/post is the endpoint Clark said
// this generates Id that can be grabbed by router
// don't need to worry about adding it to User, use another middleware for that function
boardController.createBoard = (req, res, next) => {
  console.log('inside of boardController.createBoard. Req.body: ', req.body);
  // since the schema requires these, this will be send through req body
  const { boardName, columnName, cardText } = req.body;
  // so i want to send board ID back as well, because I noticed that boards in DB has _id: ObjectId('6406897254f6667a95770854') for goblin shark
  // id of board is autogenerated
  Board.create({boardName, columnName, cardText})
    .then(data => {
      res.locals.board = data;
      next();
    })
    .catch(err => {
      return next({
        log: "error in boardController.createBoards",
        message: { err: "boardController.createBoards" + err },
      });
    });
};

boardController.getBoards = (req, res, next) => {
  console.log('running boardController.getBoards. res.locals: ', res.locals)
  let { boardIds } = res.locals;

  Board.find({_id: {$in: boardIds}})   // [ 1, 2, 3]  _id: 1, _id:2, _id:3  [{board1},{board2}]
    .then(response => {
      res.locals.boards = response;
      return next();
    })
    .catch((err) => {
      return next({
        log: "error in boardController.getBoards",
        message: { err: "boardController.getBoards" + err },
      });
    });
};
boardController.getBoard = (req, res, next) => {
  console.log('running boardController.getBoard. req.param: ', req.params)
  const { board_id } = req.params;

  Board.findById(board_id).exec()
    .then(response => {
      console.log('response: ', response);
      res.locals.board = response;
      return next();
    })
    .catch((err) => {
      return next({
        log: "error in boardController.getBoard",
        message: { err: "boardController.getBoard" + err },
      });
    });
};

module.exports = boardController;

/**
 * select *
 * from Board
 * where id in (1,2,3);
 * 
 */
